name: InFamousPermissions
main: org.extendedalpha.infamouspermissions.InFamousPermissions
version: ${project.version}${project.build.number}
author: ExileDev
description: Comprehensive permission, chat, and world management system.
softdepend: [Vault, Multiverse-Core, Essentials]
commands:
  infamousperms:
    description: InFamousPermissions root command
    usage: /<command> <args>
    aliases: [perms, perm, infamousperm, infamouspermissions]
  nick:
    description: Set a player's nickname
    usage: /<command> [player] <nick>
  prefix:
    description: Sets your prefix
    usage: /<command> <prefix>
    aliases: [pre]
  prefixreset:
    description: Reset a player's prefix
    usage: /<command> [player]
    aliases: [prer]
  realname:
    description: Get a player's real name
    usage: /<command> <player>
  suffix:
    description: Sets your suffix
    usage: /<command> <suffix>
    aliases: [suf]
  suffixreset:
    description: Reset a player's suffix
    usage: /<command> [player]
    aliases: [sufr]
permissions:
  infamouspermissions.admin:
    description: Full access to InFamousPermissions commands
    default: op
    children:
      infamouspermissions.manage.users: true
      infamouspermissions.manage.groups: true
      infamouspermissions.chat.color: true
      infamouspermissions.chat.formatting: true
      infamouspermissions.chat.rainbow: true
      infamouspermissions.cmd.prefix: true
      infamouspermissions.cmd.reload: true
      infamouspermissions.cmd.save: true
      infamouspermissions.cmd.suffix: true
      infamouspermissions.cmd.nick: true
      infamouspermissions.cmd.realname: true
      infamouspermissions.cmd.reload: true
      infamouspermissions.cmd.save: true
      infamouspermissions.moderator: true
  infamouspermissions.moderator:
    description: Allows access to commands meant for mods
    default: false
    children:
      infamouspermissions.cmd.prefix.reset: true
      infamouspermissions.cmd.prefix.reset.others: true
      infamouspermissions.cmd.suffix.reset: true
      infamouspermissions.cmd.suffix.reset.others: true
  infamouspermissions.manage.users:
    description: Manage users' permissions
    default: false
    children:
      infamouspermissions.user.view.info: true
      infamouspermissions.user.add.subgroup: true
      infamouspermissions.user.add.permission: true
      infamouspermissions.user.remove.subgroup: true
      infamouspermissions.user.remove.permission: true
      infamouspermissions.user.set.group: true
      infamouspermissions.user.set.prefix: true
      infamouspermissions.user.set.suffix: true
      infamouspermissions.user.set.option: true
      infamouspermissions.user.has.permission: true
      infamouspermissions.user.has.group: true
      infamouspermissions.user.has.option: true
      infamouspermissions.user.list.permissions: true
      infamouspermissions.user.reset: true
  infamouspermissions.user.view.info:
    default: false
  infamouspermissions.user.add.subgroup:
    default: false
  infamouspermissions.user.add.permission:
    default: false
  infamouspermissions.user.remove.subgroup:
    default: false
  infamouspermissions.user.remove.permission:
    default: false
  infamouspermissions.user.set.group:
    default: false
  infamouspermissions.user.set.prefix:
    default: false
  infamouspermissions.user.set.suffix:
    default: false
  infamouspermissions.user.set.option:
    default: false
  infamouspermissions.user.has.permission:
    default: false
  infamouspermissions.user.has.group:
    default: false
  infamouspermissions.user.has.option:
    default: false
  infamouspermissions.user.list.permissions:
    default: false
  infamouspermissions.user.reset:
    default: false
  infamouspermissions.manage.groups:
    description: Manage groups' permissions
    default: false
    children:
      infamouspermissions.group.view.info: true
      infamouspermissions.group.add.permission: true
      infamouspermissions.group.remove.permission: true
      infamouspermissions.group.set.prefix: true
      infamouspermissions.group.set.suffix: true
      infamouspermissions.group.set.option: true
      infamouspermissions.group.has.permission: true
      infamouspermissions.group.has.option: true
      infamouspermissions.group.list.permissions: true
      infamouspermissions.group.list.users: true
      infamouspermissions.group.list: true
      infamouspermissions.group.create: true
  infamouspermissions.group.view.info:
    default: false
  infamouspermissions.group.add.permission:
    default: false
  infamouspermissions.group.remove.permission:
    default: false
  infamouspermissions.group.set.prefix:
    default: false
  infamouspermissions.group.set.suffix:
    default: false
  infamouspermissions.group.set.option:
    default: false
  infamouspermissions.group.has.permission:
    default: false
  infamouspermissions.group.has.option:
    default: false
  infamouspermissions.group.list.users:
    default: false
  infamouspermissions.group.list.permissions:
    default: false
  infamouspermissions.group.list:
    default: false
  infamouspermissions.group.create:
    default: false
  infamouspermissions.chat.color:
    default: false
  infamouspermissions.chat.formatting:
    default: false
  infamouspermissions.chat.rainbow:
    default: false
  infamouspermissions.cmd.prefix:
    default: false
  infamouspermissions.cmd.prefix.reset:
    default: false
  infamouspermissions.cmd.prefix.reset.others:
    default: false
  infamouspermissions.cmd.suffix:
    default: false
  infamouspermissions.cmd.suffix.reset:
    default: false
  infamouspermissions.cmd.suffix.reset.others:
    default: false
  infamouspermissions.cmd.nick:
    default: false
  infamouspermissions.cmd.realname:
    default: false
  infamouspermissions.cmd.reload:
    default: false
  infamouspermissions.cmd.save:
    default: false
  infamouspermissions.cmd.version:
    default: true