name: Skyblock
main: org.extendedalpha.skyblock.Skyblock
version: ${version}
description: Skyblock Plugin
author: Tastybento
depend: [Vault]
softdepend: [Herochat]
load: startup
loadbefore: [Multiverse-Core]
commands:
    island:
        description: Main player command
        aliases: [is, island]
        usage:  |
             /island help
    sbadmin:
        description: Admin commands
        usage:  |
            /sbadmin
    sbc:
        description: Game challenges
        aliases: [c, challenge, sbchallenge, challenges]
        usage:  |  
            /challenge
permissions:    
  skyblock.*:
    children:
      skyblock.island.*:
        children:
          skyblock.island.go:
            description: Allow teleporting to player island
            default: true
          skyblock.island.create:
            description: Let the player use the /island command
            default: true
          skyblock.island.info:
            description: Let the player check their island level
            default: true
          skyblock.island.topten:
            description: Let the player see the top ten list
            default: true
          skyblock.island.sethome:
            description: Let the player set their island teleport point
            default: true
          skyblock.island.challenges:
            description: Let the player use the /challenges command
            default: true
          skyblock.island.warp:
            description: Let the player use /island warp to warp to a players island
            default: true
          skyblock.island.addwarp:
            description: Let the player place a Welcome warp sign
            default: true
          skyblock.island.shop:
            description: Allows usage of the shop
            default: true
          skyblock.island.controlpanel:
            description: Allows usage of the island GUI
            default: true
          skyblock.island.biomes:
            description: Allows biome changing
            default: true
          skyblock.island.lock:
            description: Allows island locking
            default: false
          skyblock.island.expel:
            description: Allows expelling of visitors
            default: true
          skyblock.island.ban:
            description: Allows banning of visitors
            default: false
          skyblock.island.settings:
            description: Player can see server settings
            default: true
          skyblock.island.lang:
            description: Player can select a language
            default: true
      skyblock.team.*:
        children:
          skyblock.team.create:
            description: Let a player invite other players to join a team
            default: true
          skyblock.team.kick:
            description: Let a player kick other players
            default: true
          skyblock.team.makeleader:
            description: Let a player make another player leader of the team
            default: true
          skyblock.team.join:
            description: Let a player join another player's team
            default: true
          skyblock.team.chat:
            description: Allow player to use team chat
            default: true
      skyblock.coop:
        description: Allows player to use the coop command
        default: false    
      skyblock.craft.*:
        children:
          skyblock.craft.enderchest:
            description: Allow crafting and use of enderchests in skyblock
            default: false
      skyblock.settings.*:
        children:
          skyblock.settings.allowAnvilUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowArmorStandUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowBeaconAccess:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowBedUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowBreakBlocks:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowBreeding:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowBrewing:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowBucketUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowChestAccess:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowCrafting:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowCropTrample:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowDoorUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowEnchanting:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowEnderPearls:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowFurnaceUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowGateUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowHorseInvAccess:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowHorseRiding:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowHurtMobs:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowLeashUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowLeverButtonUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowMusic:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowPlaceBlocks:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowPortalUse:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowPressurePlate:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowPvP:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowNetherPvP:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowRedStone:
            description: Allow player to change this island guard setting
            default: false
          skyblock.settings.allowShearing:
            description: Allow player to change this island guard setting
            default: false
      skyblock.mod.*:
        children:
          skyblock.mod.topten:
            description: Let a moderator update the top ten list
            default: op
          skyblock.mod.info:
            description: Let a moderator see info on a player
            default: op
          skyblock.mod.challenges:
            description: Let a moderator access challenge commands 
            default: op
          skyblock.mod.noburn:
            description: Gives mod immunity to acid
            default: false
          skyblock.mod.resethome:
            description: Allows setting or reseting of a player's home position
            default: op
          skyblock.mod.clearreset:
            description: Allow clearing of island reset limit
            default: false
          skyblock.mod.tp:
            description: Allows teleport to an island
            default: op
          skyblock.mod.tpnether:
            description: Allows teleport to a nether island
            default: op
          skyblock.mod.bypassprotect:
            description: Allow moderator to bypass island protection
            default: op
          skyblock.mod.setbiome:
            description: Allows setting player island biomes
            default: op
          skyblock.mod.topbreeders:
            description: Lists most populated islands current loaded
            default: op
          skyblock.mod.lock:
            description: Locks or unlocks an island
            default: op
          skyblock.mod.bypasslock:
            description: Bypasses an island lock
            default: op
          skyblock.mod.signadmin:
            description: Enables warp sign admin commands
            default: op
          skyblock.mod.spy:
            description: Spy on team chats
            default: false
          skyblock.mod.excludetopten:
            description: Exclude player from the top ten list
            default: false
          skyblock.mod.removesign:
            description: Gives ability to remove warp signs
            default: false
      skyblock.admin.*:
        children:
          skyblock.admin.reload:
            description: Reload the config.yml
            default: op
          skyblock.admin.delete:
            description: Let a player completely remove a player (including island)
            default: op
          skyblock.admin.deleteisland:
            description: Let a player completely remove the island the player is on
            default: op
          skyblock.admin.register:
            description: Let a player register the nearest island to another player.
            default: op
          skyblock.admin.unregister:
            description: Removes a player from an island without deleting the island blocks.
            default: op
          skyblock.admin.purge:
            description: Let a player purge old islands.
            default: op
          skyblock.admin.noburn:
            description: Gives admin immunity to acid
            default: false
          skyblock.admin.setspawn:
            description: Allows use of spawn tools
            default: op
          skyblock.admin.setrange:
            description: Allows setting of island protection range
            default: op
          skyblock.admin.topbreeders:
            description: Lists most populated islands current loaded
            default: op
